-- =====================================================================
-- riveraurbano.com — Datos iniciales: idiomas, textos (es/en) y configuración
-- Se puede volver a ejecutar sin riesgo: solo agrega lo que falte y NO borra tus cambios.
-- =====================================================================

SET NAMES utf8mb4;
USE rivera;

INSERT INTO idiomas (codigo, nombre, locale, activo, por_defecto, orden) VALUES
  ('es','Español','es_MX',1,1,1),
  ('en','English','en_US',1,0,2)
ON DUPLICATE KEY UPDATE nombre=VALUES(nombre), locale=VALUES(locale);

INSERT INTO configuracion (clave, valor, descripcion) VALUES
  ('whatsapp', '526860000000', 'Número con lada internacional, solo dígitos (52 = México)'),
  ('telefono', '686 000 0000', 'Teléfono como se muestra en pantalla'),
  ('correo', 'contacto@riveraurbano.com', 'Correo de contacto'),
  ('youtube_id', '', 'ID de YouTube del video del dron (vacío = usar assets/video/dron.mp4)'),
  ('video_portada', '/assets/video/dron-corto.mp4', 'Clip corto sin audio para el fondo de la portada (vacío = solo imagen)'),
  ('mapa', 'Calle Novena y Calzada Cetys, Mexicali, B.C.', 'Búsqueda o coordenadas para el mapa (ej. 32.6245,-115.4523)'),
  ('url_base', 'https://riveraurbano.com', 'URL pública del sitio, sin diagonal final')
ON DUPLICATE KEY UPDATE descripcion=VALUES(descripcion);

INSERT IGNORE INTO textos (clave, idioma, valor) VALUES
  ('meta.titulo', 'es', 'Terrenos en renta en Calle Novena, Mexicali | Rivera Urbano'),
  ('meta.titulo', 'en', 'Land for lease on Calle Novena, Mexicali | Rivera Urbano'),
  ('meta.descripcion', 'es', 'Dos terrenos en renta sobre Calle Novena, a pasos de Calzada Cetys y Carretera al Aeropuerto, en Mexicali, B.C. Ideales para comercio, servicios o estacionamiento. Mira el video aéreo y contáctanos por WhatsApp.'),
  ('meta.descripcion', 'en', 'Two lots for lease on Calle Novena, steps from Calzada Cetys and the Airport Highway in Mexicali, Baja California. Ideal for retail, services or parking. Watch the aerial video and contact us on WhatsApp.'),
  ('og.titulo', 'es', 'Terrenos en renta en Calle Novena, Mexicali'),
  ('og.titulo', 'en', 'Land for lease on Calle Novena, Mexicali'),
  ('og.descripcion', 'es', 'Dos terrenos frente a frente sobre Calle Novena, a pasos de Calzada Cetys. Mira el video aéreo y agenda una visita.'),
  ('og.descripcion', 'en', 'Two facing lots on Calle Novena, steps from Calzada Cetys. Watch the aerial video and book a visit.'),
  ('nav.ir_inicio', 'es', 'Rivera Urbano, ir al inicio'),
  ('nav.ir_inicio', 'en', 'Rivera Urbano, go to top'),
  ('nav.abrir_menu', 'es', 'Abrir menú'),
  ('nav.abrir_menu', 'en', 'Open menu'),
  ('nav.cerrar_menu', 'es', 'Cerrar menú'),
  ('nav.cerrar_menu', 'en', 'Close menu'),
  ('nav.principal', 'es', 'Principal'),
  ('nav.principal', 'en', 'Main'),
  ('nav.idioma', 'es', 'Idioma'),
  ('nav.idioma', 'en', 'Language'),
  ('nav.terrenos', 'es', 'Terrenos'),
  ('nav.terrenos', 'en', 'Lots'),
  ('nav.video', 'es', 'Video aéreo'),
  ('nav.video', 'en', 'Aerial video'),
  ('nav.propuesta', 'es', 'Propuesta'),
  ('nav.propuesta', 'en', 'Proposal'),
  ('nav.preguntas', 'es', 'Preguntas'),
  ('nav.preguntas', 'en', 'FAQ'),
  ('nav.contacto', 'es', 'Contacto'),
  ('nav.contacto', 'en', 'Contact'),
  ('nav.whatsapp', 'es', 'WhatsApp'),
  ('nav.whatsapp', 'en', 'WhatsApp'),
  ('hero.titulo', 'es', 'Terrenos en renta sobre Calle Novena'),
  ('hero.titulo', 'en', 'Land for lease on Calle Novena'),
  ('hero.sub', 'es', 'Dos predios frente a frente sobre Calle Novena, a pasos del cruce con Calzada Cetys y Carretera al Aeropuerto. Una zona de paso diario en Mexicali, lista para tu negocio.'),
  ('hero.sub', 'en', 'Two facing lots on Calle Novena, steps from the Calzada Cetys and Airport Highway intersection. A busy everyday route in Mexicali, ready for your business.'),
  ('hero.btn_info', 'es', 'Pedir información'),
  ('hero.btn_info', 'en', 'Request information'),
  ('hero.btn_video', 'es', 'Ver video aéreo'),
  ('hero.btn_video', 'en', 'Watch aerial video'),
  ('hero.dato1', 'es', '2 terrenos disponibles'),
  ('hero.dato1', 'en', '2 lots available'),
  ('hero.dato2', 'es', 'Frente a Calle Novena'),
  ('hero.dato2', 'en', 'Frontage on Calle Novena'),
  ('hero.dato3', 'es', 'Mexicali, B.C.'),
  ('hero.dato3', 'en', 'Mexicali, B.C.'),
  ('terrenos.titulo', 'es', 'Dos terrenos, uno a cada lado de la Novena'),
  ('terrenos.titulo', 'en', 'Two lots, one on each side of Calle Novena'),
  ('terrenos.intro', 'es', 'Toca un lote en el croquis para ver sus datos. Puedes rentar uno o los dos.'),
  ('terrenos.intro', 'en', 'Tap a lot on the map to see its details. You can lease one or both.'),
  ('croquis.titulo', 'es', 'Croquis de ubicación: los dos terrenos están sobre Calle Novena, al sur de Calzada Cetys. El Lote A está del lado poniente, junto al CEDIS de Coppel y un car wash; el Lote B está del lado oriente, detrás de la gasolinera bp.'),
  ('croquis.titulo', 'en', 'Location sketch: both lots are on Calle Novena, south of Calzada Cetys. Lot A is on the west side, next to the Coppel distribution center and a car wash; Lot B is on the east side, behind the bp gas station.'),
  ('croquis.nota', 'es', 'Croquis ilustrativo, no está a escala. Las medidas exactas se entregan con el plano.'),
  ('croquis.nota', 'en', 'Illustrative sketch, not to scale. Exact measurements come with the site plan.'),
  ('croquis.ver_lote', 'es', 'Ver datos del {lote}'),
  ('croquis.ver_lote', 'en', 'See details for {lote}'),
  ('croquis.elegir', 'es', 'Elegir lote'),
  ('croquis.elegir', 'en', 'Choose a lot'),
  ('lote.a.nombre', 'es', 'Lote A'),
  ('lote.a.nombre', 'en', 'Lot A'),
  ('lote.a.donde', 'es', 'Lado poniente de Calle Novena, junto al CEDIS de Coppel'),
  ('lote.a.donde', 'en', 'West side of Calle Novena, next to the Coppel distribution center'),
  ('lote.b.nombre', 'es', 'Lote B'),
  ('lote.b.nombre', 'en', 'Lot B'),
  ('lote.b.donde', 'es', 'Lado oriente de Calle Novena, junto a la gasolinera bp'),
  ('lote.b.donde', 'en', 'East side of Calle Novena, next to the bp gas station'),
  ('lote.campo.superficie', 'es', 'Superficie'),
  ('lote.campo.superficie', 'en', 'Area'),
  ('lote.campo.frente', 'es', 'Frente a Calle Novena'),
  ('lote.campo.frente', 'en', 'Frontage on Calle Novena'),
  ('lote.campo.fondo', 'es', 'Fondo'),
  ('lote.campo.fondo', 'en', 'Depth'),
  ('lote.campo.uso_suelo', 'es', 'Uso de suelo'),
  ('lote.campo.uso_suelo', 'en', 'Zoning'),
  ('lote.campo.servicios', 'es', 'Servicios'),
  ('lote.campo.servicios', 'en', 'Utilities'),
  ('lote.campo.renta', 'es', 'Renta'),
  ('lote.campo.renta', 'en', 'Rent'),
  ('lote.a.superficie', 'es', 'Por confirmar m²'),
  ('lote.a.superficie', 'en', 'To be confirmed (m²)'),
  ('lote.a.frente', 'es', 'Por confirmar m'),
  ('lote.a.frente', 'en', 'To be confirmed (m)'),
  ('lote.a.fondo', 'es', 'Por confirmar m'),
  ('lote.a.fondo', 'en', 'To be confirmed (m)'),
  ('lote.a.uso_suelo', 'es', 'Por confirmar'),
  ('lote.a.uso_suelo', 'en', 'To be confirmed'),
  ('lote.a.servicios', 'es', 'Por confirmar'),
  ('lote.a.servicios', 'en', 'To be confirmed'),
  ('lote.a.renta', 'es', 'Consultar'),
  ('lote.a.renta', 'en', 'Ask us'),
  ('lote.b.superficie', 'es', 'Por confirmar m²'),
  ('lote.b.superficie', 'en', 'To be confirmed (m²)'),
  ('lote.b.frente', 'es', 'Por confirmar m'),
  ('lote.b.frente', 'en', 'To be confirmed (m)'),
  ('lote.b.fondo', 'es', 'Por confirmar m'),
  ('lote.b.fondo', 'en', 'To be confirmed (m)'),
  ('lote.b.uso_suelo', 'es', 'Por confirmar'),
  ('lote.b.uso_suelo', 'en', 'To be confirmed'),
  ('lote.b.servicios', 'es', 'Por confirmar'),
  ('lote.b.servicios', 'en', 'To be confirmed'),
  ('lote.b.renta', 'es', 'Consultar'),
  ('lote.b.renta', 'en', 'Ask us'),
  ('lote.pendiente', 'es', 'Por confirmar'),
  ('lote.pendiente', 'en', 'To be confirmed'),
  ('lote.btn_preguntar', 'es', 'Preguntar por el {lote}'),
  ('lote.btn_preguntar', 'en', 'Ask about {lote}'),
  ('video.titulo', 'es', 'Recorre los terrenos desde el aire'),
  ('video.titulo', 'en', 'Tour the lots from above'),
  ('video.intro', 'es', 'Video grabado con dron. Mira los accesos, el tráfico de la Novena y lo que hay alrededor antes de venir.'),
  ('video.intro', 'en', 'Drone footage. See the access points, the traffic on Calle Novena and the surroundings before you visit.'),
  ('video.sin_archivo', 'es', 'El video aéreo estará disponible muy pronto. Mientras, pídelo por WhatsApp y te lo enviamos.'),
  ('video.sin_archivo', 'en', 'The aerial video is coming soon. In the meantime, ask for it on WhatsApp and we''ll send it to you.'),
  ('video.no_soportado', 'es', 'Tu navegador no puede reproducir este video.'),
  ('video.no_soportado', 'en', 'Your browser can''t play this video.'),
  ('video.iframe', 'es', 'Video aéreo de los terrenos'),
  ('video.iframe', 'en', 'Aerial video of the lots'),
  ('video.pie', 'es', '¿Te gustó lo que viste? Agenda una visita al terreno.'),
  ('video.pie', 'en', 'Like what you see? Book a site visit.'),
  ('video.btn_visita', 'es', 'Agendar visita'),
  ('video.btn_visita', 'en', 'Book a visit'),
  ('propuesta.titulo', 'es', '¿Qué puedes poner aquí?'),
  ('propuesta.titulo', 'en', 'What could you build here?'),
  ('propuesta.intro', 'es', 'Por aquí pasa el tráfico que entra y sale de Calzada Cetys y de la Carretera al Aeropuerto, y el CEDIS de Coppel, la gasolinera y el car wash ya generan movimiento todo el día. Estos giros sacan provecho de ese flujo:'),
  ('propuesta.intro', 'en', 'Traffic to and from Calzada Cetys and the Airport Highway passes right by, and the Coppel distribution center, the gas station and the car wash keep the area busy all day. These businesses make the most of that flow:'),
  ('uso.1.titulo', 'es', 'Plaza o local comercial'),
  ('uso.1.titulo', 'en', 'Retail strip or store'),
  ('uso.1.texto', 'es', 'Construye locales y súbelos a renta, o instala tu propia tienda con frente a la avenida.'),
  ('uso.1.texto', 'en', 'Build units to sublease, or open your own store facing the street.'),
  ('uso.2.titulo', 'es', 'Comida y café con autoservicio'),
  ('uso.2.titulo', 'en', 'Food and coffee drive-thru'),
  ('uso.2.texto', 'es', 'Cafetería, restaurante o drive-thru que vive del paso de autos a toda hora.'),
  ('uso.2.texto', 'en', 'Coffee shop, restaurant or drive-thru fed by traffic all day long.'),
  ('uso.3.titulo', 'es', 'Servicios para el auto'),
  ('uso.3.titulo', 'en', 'Automotive services'),
  ('uso.3.texto', 'es', 'Autolavado, llantera, lubricentro o venta de autos en lote abierto.'),
  ('uso.3.texto', 'en', 'Car wash, tire shop, quick lube or an open-air car lot.'),
  ('uso.4.titulo', 'es', 'Estacionamiento'),
  ('uso.4.titulo', 'en', 'Parking'),
  ('uso.4.texto', 'es', 'Pensión o estacionamiento de paga con inversión mínima: se nivela, se cerca y opera.'),
  ('uso.4.texto', 'en', 'Monthly or paid parking with minimal investment: grade it, fence it and open.'),
  ('uso.5.titulo', 'es', 'Farmacia, consultorio o clínica'),
  ('uso.5.titulo', 'en', 'Pharmacy, doctor''s office or clinic'),
  ('uso.5.texto', 'es', 'Servicios de salud que buscan visibilidad y fácil acceso en auto.'),
  ('uso.5.texto', 'en', 'Health services that need visibility and easy car access.'),
  ('uso.6.titulo', 'es', 'Food trucks y eventos'),
  ('uso.6.titulo', 'en', 'Food trucks and events'),
  ('uso.6.texto', 'es', 'Parque de food trucks, bazar de fin de semana o espacio para eventos por temporada.'),
  ('uso.6.texto', 'en', 'Food truck park, weekend market or seasonal event space.'),
  ('esquemas.titulo', 'es', 'Formas de rentar'),
  ('esquemas.titulo', 'en', 'Lease options'),
  ('esquemas.intro', 'es', 'Elige la que se acomode a tu proyecto. Los términos finales se platican en persona.'),
  ('esquemas.intro', 'en', 'Pick the one that fits your project. Final terms are agreed in person.'),
  ('esquema.1.titulo', 'es', 'Renta mensual'),
  ('esquema.1.titulo', 'en', 'Monthly lease'),
  ('esquema.1.para', 'es', 'Para negocios que se instalan con estructura ligera.'),
  ('esquema.1.para', 'en', 'For businesses that set up with light structures.'),
  ('esquema.1.li1', 'es', 'Contrato desde 12 meses'),
  ('esquema.1.li1', 'en', 'Contracts from 12 months'),
  ('esquema.1.li2', 'es', 'Terreno entregado limpio'),
  ('esquema.1.li2', 'en', 'Lot delivered clean'),
  ('esquema.1.li3', 'es', 'Ideal para estacionamiento, autolavado o lote de autos'),
  ('esquema.1.li3', 'en', 'Ideal for parking, car wash or car lot'),
  ('esquema.2.titulo', 'es', 'Largo plazo para construir'),
  ('esquema.2.titulo', 'en', 'Long-term ground lease'),
  ('esquema.2.para', 'es', 'Para cadenas, franquicias o inversionistas que van a edificar.'),
  ('esquema.2.para', 'en', 'For chains, franchises or investors planning to build.'),
  ('esquema.2.li1', 'es', 'Contratos de 5 a 20 años'),
  ('esquema.2.li1', 'en', '5 to 20 year terms'),
  ('esquema.2.li2', 'es', 'Meses de gracia durante la obra, a negociar'),
  ('esquema.2.li2', 'en', 'Rent-free months during construction, negotiable'),
  ('esquema.2.li3', 'es', 'Apoyo con la información para tus permisos'),
  ('esquema.2.li3', 'en', 'Help with property information for your permits'),
  ('esquema.3.titulo', 'es', 'Renta temporal'),
  ('esquema.3.titulo', 'en', 'Short-term lease'),
  ('esquema.3.para', 'es', 'Para temporadas, eventos o proyectos de prueba.'),
  ('esquema.3.para', 'en', 'For seasons, events or pilot projects.'),
  ('esquema.3.li1', 'es', 'Por semana, mes o temporada'),
  ('esquema.3.li1', 'en', 'By the week, month or season'),
  ('esquema.3.li2', 'es', 'Bazares, food trucks, ventas de temporada'),
  ('esquema.3.li2', 'en', 'Markets, food trucks, seasonal sales'),
  ('esquema.3.li3', 'es', 'Buena forma de probar la ubicación'),
  ('esquema.3.li3', 'en', 'A good way to test the location'),
  ('esquema.btn', 'es', 'Me interesa'),
  ('esquema.btn', 'en', 'I''m interested'),
  ('pasos.titulo', 'es', 'Cómo rentar, paso a paso'),
  ('pasos.titulo', 'en', 'How to lease, step by step'),
  ('paso.1.titulo', 'es', 'Escríbenos'),
  ('paso.1.titulo', 'en', 'Reach out'),
  ('paso.1.texto', 'es', 'Cuéntanos qué giro tienes en mente y qué lote te interesa.'),
  ('paso.1.texto', 'en', 'Tell us what kind of business you have in mind and which lot you like.'),
  ('paso.2.titulo', 'es', 'Visita el terreno'),
  ('paso.2.titulo', 'en', 'Visit the lot'),
  ('paso.2.texto', 'es', 'Te acompañamos al predio y resolvemos tus dudas en sitio.'),
  ('paso.2.texto', 'en', 'We''ll walk the site with you and answer your questions there.'),
  ('paso.3.titulo', 'es', 'Recibe la propuesta'),
  ('paso.3.titulo', 'en', 'Get the proposal'),
  ('paso.3.texto', 'es', 'Te enviamos precio, plazo y condiciones por escrito.'),
  ('paso.3.texto', 'en', 'We send you price, term and conditions in writing.'),
  ('paso.4.titulo', 'es', 'Firma y arranca'),
  ('paso.4.titulo', 'en', 'Sign and start'),
  ('paso.4.texto', 'es', 'Firmamos contrato y te entregamos el terreno.'),
  ('paso.4.texto', 'en', 'We sign the lease and hand over the lot.'),
  ('faq.titulo', 'es', 'Preguntas frecuentes'),
  ('faq.titulo', 'en', 'Frequently asked questions'),
  ('faq.1.p', 'es', '¿Cuánto cuesta la renta?'),
  ('faq.1.p', 'en', 'How much is the rent?'),
  ('faq.1.r', 'es', 'Depende del lote, del plazo y del uso que le vayas a dar. Escríbenos con tu proyecto y te mandamos una propuesta por escrito.'),
  ('faq.1.r', 'en', 'It depends on the lot, the term and your intended use. Send us your project and we''ll reply with a written proposal.'),
  ('faq.2.p', 'es', '¿Puedo rentar los dos terrenos?'),
  ('faq.2.p', 'en', 'Can I lease both lots?'),
  ('faq.2.r', 'es', 'Sí. Puedes rentar uno o ambos; para los dos lotes juntos hay condiciones especiales.'),
  ('faq.2.r', 'en', 'Yes. You can lease one or both; there are special terms for leasing them together.'),
  ('faq.3.p', 'es', '¿Puedo construir en el terreno?'),
  ('faq.3.p', 'en', 'Can I build on the lot?'),
  ('faq.3.r', 'es', 'Sí, con contrato a largo plazo. Revisamos juntos tu proyecto y te compartimos la información del predio para tus permisos ante el municipio.'),
  ('faq.3.r', 'en', 'Yes, with a long-term lease. We''ll review your project together and share the property information you need for city permits.'),
  ('faq.4.p', 'es', '¿Qué servicios tiene?'),
  ('faq.4.p', 'en', 'What utilities are available?'),
  ('faq.4.r', 'es', 'Revisa la ficha de cada lote arriba. Si necesitas un dato que no aparece, pregúntanos y te lo confirmamos.'),
  ('faq.4.r', 'en', 'Check each lot''s details above. If something you need isn''t listed, ask us and we''ll confirm it.'),
  ('faq.5.p', 'es', '¿Qué documentos piden para rentar?'),
  ('faq.5.p', 'en', 'What documents do I need?'),
  ('faq.5.r', 'es', 'Identificación oficial, comprobante de domicilio y, si rentas como empresa, acta constitutiva y poder del representante. Para contratos largos podemos pedir aval o depósito en garantía.'),
  ('faq.5.r', 'en', 'Official ID, proof of address and, for companies, articles of incorporation and the representative''s power of attorney. Long-term leases may require a guarantor or security deposit.'),
  ('faq.6.p', 'es', '¿Puedo ver el terreno antes?'),
  ('faq.6.p', 'en', 'Can I see the lot first?'),
  ('faq.6.r', 'es', 'Claro. Agenda una visita por WhatsApp o por teléfono y te acompañamos.'),
  ('faq.6.r', 'en', 'Of course. Book a visit on WhatsApp or by phone and we''ll meet you there.'),
  ('contacto.titulo', 'es', 'Hablemos de tu proyecto'),
  ('contacto.titulo', 'en', 'Let''s talk about your project'),
  ('contacto.intro', 'es', 'Escríbenos por el medio que prefieras y te respondemos a la brevedad.'),
  ('contacto.intro', 'en', 'Reach us however you prefer and we''ll get back to you shortly.'),
  ('canal.whatsapp', 'es', 'WhatsApp'),
  ('canal.whatsapp', 'en', 'WhatsApp'),
  ('canal.llamar', 'es', 'Llamar'),
  ('canal.llamar', 'en', 'Call'),
  ('canal.correo', 'es', 'Correo'),
  ('canal.correo', 'en', 'Email'),
  ('canal.ubicacion', 'es', 'Ubicación · abrir en Google Maps'),
  ('canal.ubicacion', 'en', 'Location · open in Google Maps'),
  ('canal.direccion', 'es', 'Calle Novena y Calzada Cetys, Mexicali'),
  ('canal.direccion', 'en', 'Calle Novena & Calzada Cetys, Mexicali'),
  ('mapa.titulo', 'es', 'Mapa de la ubicación de los terrenos'),
  ('mapa.titulo', 'en', 'Map showing the location of the lots'),
  ('form.titulo', 'es', 'Solicita información'),
  ('form.titulo', 'en', 'Request information'),
  ('form.intro', 'es', 'Llena lo que sepas y envíalo por WhatsApp o por correo. Nada se guarda en este sitio.'),
  ('form.intro', 'en', 'Fill in what you know and send it by WhatsApp or email. Nothing is stored on this site.'),
  ('form.nombre', 'es', 'Nombre'),
  ('form.nombre', 'en', 'Name'),
  ('form.nombre_error', 'es', 'Escribe tu nombre.'),
  ('form.nombre_error', 'en', 'Please enter your name.'),
  ('form.telefono', 'es', 'Teléfono'),
  ('form.telefono', 'en', 'Phone'),
  ('form.telefono_error', 'es', 'Escribe un teléfono para contactarte.'),
  ('form.telefono_error', 'en', 'Please enter a phone number.'),
  ('form.empresa', 'es', 'Empresa o marca (opcional)'),
  ('form.empresa', 'en', 'Company or brand (optional)'),
  ('form.lote', 'es', 'Lote de interés'),
  ('form.lote', 'en', 'Lot of interest'),
  ('form.lote.a', 'es', 'Lote A (junto a Coppel)'),
  ('form.lote.a', 'en', 'Lot A (next to Coppel)'),
  ('form.lote.b', 'es', 'Lote B (junto a la bp)'),
  ('form.lote.b', 'en', 'Lot B (next to bp)'),
  ('form.lote.ambos', 'es', 'Los dos'),
  ('form.lote.ambos', 'en', 'Both'),
  ('form.lote.nose', 'es', 'Aún no sé'),
  ('form.lote.nose', 'en', 'Not sure yet'),
  ('form.uso', 'es', '¿Para qué lo usarías?'),
  ('form.uso', 'en', 'What would you use it for?'),
  ('form.uso.1', 'es', 'Local o plaza comercial'),
  ('form.uso.1', 'en', 'Store or retail strip'),
  ('form.uso.2', 'es', 'Comida / café / drive-thru'),
  ('form.uso.2', 'en', 'Food / coffee / drive-thru'),
  ('form.uso.3', 'es', 'Servicios para el auto'),
  ('form.uso.3', 'en', 'Automotive services'),
  ('form.uso.4', 'es', 'Estacionamiento'),
  ('form.uso.4', 'en', 'Parking'),
  ('form.uso.5', 'es', 'Salud (farmacia, consultorio)'),
  ('form.uso.5', 'en', 'Health (pharmacy, clinic)'),
  ('form.uso.6', 'es', 'Food trucks o eventos'),
  ('form.uso.6', 'en', 'Food trucks or events'),
  ('form.uso.7', 'es', 'Otro'),
  ('form.uso.7', 'en', 'Other'),
  ('form.plazo', 'es', 'Plazo'),
  ('form.plazo', 'en', 'Term'),
  ('form.plazo.1', 'es', 'Temporal (menos de 1 año)'),
  ('form.plazo.1', 'en', 'Short-term (under 1 year)'),
  ('form.plazo.2', 'es', '1 a 5 años'),
  ('form.plazo.2', 'en', '1 to 5 years'),
  ('form.plazo.3', 'es', 'Más de 5 años (para construir)'),
  ('form.plazo.3', 'en', 'Over 5 years (to build)'),
  ('form.plazo.4', 'es', 'Por definir'),
  ('form.plazo.4', 'en', 'Undecided'),
  ('form.mensaje', 'es', 'Mensaje (opcional)'),
  ('form.mensaje', 'en', 'Message (optional)'),
  ('form.mensaje_ph', 'es', 'Cuéntanos de tu proyecto, horario para visitar, etc.'),
  ('form.mensaje_ph', 'en', 'Tell us about your project, when you''d like to visit, etc.'),
  ('form.btn_whats', 'es', 'Enviar por WhatsApp'),
  ('form.btn_whats', 'en', 'Send via WhatsApp'),
  ('form.btn_correo', 'es', 'Enviar por correo'),
  ('form.btn_correo', 'en', 'Send via email'),
  ('form.aviso', 'es', 'Tus datos solo se usan para responder a tu solicitud.'),
  ('form.aviso', 'en', 'Your details are only used to reply to your request.'),
  ('wa.general', 'es', 'Hola, vi riveraurbano.com y me interesa rentar un terreno en Calle Novena.'),
  ('wa.general', 'en', 'Hi, I saw riveraurbano.com and I''m interested in leasing a lot on Calle Novena.'),
  ('wa.info', 'es', 'Hola, vi riveraurbano.com y quiero información de los terrenos en Calle Novena.'),
  ('wa.info', 'en', 'Hi, I saw riveraurbano.com and I''d like information about the lots on Calle Novena.'),
  ('wa.video', 'es', 'Hola, vi el video de los terrenos en Calle Novena y quiero agendar una visita.'),
  ('wa.video', 'en', 'Hi, I watched the video of the lots on Calle Novena and I''d like to book a visit.'),
  ('wa.esquema.1', 'es', 'Hola, me interesa la renta mensual de un terreno en Calle Novena.'),
  ('wa.esquema.1', 'en', 'Hi, I''m interested in a monthly lease for a lot on Calle Novena.'),
  ('wa.esquema.2', 'es', 'Hola, me interesa rentar a largo plazo un terreno en Calle Novena para construir.'),
  ('wa.esquema.2', 'en', 'Hi, I''m interested in a long-term ground lease on Calle Novena to build.'),
  ('wa.esquema.3', 'es', 'Hola, me interesa una renta temporal de un terreno en Calle Novena.'),
  ('wa.esquema.3', 'en', 'Hi, I''m interested in a short-term lease for a lot on Calle Novena.'),
  ('wa.lote', 'es', 'Hola, me interesa el {lote} ({donde}). ¿Me pueden dar informes?'),
  ('wa.lote', 'en', 'Hi, I''m interested in {lote} ({donde}). Could you send me details?'),
  ('msg.encabezado', 'es', 'Hola, quiero información para rentar un terreno en Calle Novena.'),
  ('msg.encabezado', 'en', 'Hi, I''d like information about leasing a lot on Calle Novena.'),
  ('msg.nombre', 'es', 'Nombre'),
  ('msg.nombre', 'en', 'Name'),
  ('msg.telefono', 'es', 'Teléfono'),
  ('msg.telefono', 'en', 'Phone'),
  ('msg.empresa', 'es', 'Empresa'),
  ('msg.empresa', 'en', 'Company'),
  ('msg.lote', 'es', 'Lote'),
  ('msg.lote', 'en', 'Lot'),
  ('msg.uso', 'es', 'Uso'),
  ('msg.uso', 'en', 'Use'),
  ('msg.plazo', 'es', 'Plazo'),
  ('msg.plazo', 'en', 'Term'),
  ('msg.mensaje', 'es', 'Mensaje'),
  ('msg.mensaje', 'en', 'Message'),
  ('correo.asunto', 'es', 'Renta de terreno en Calle Novena'),
  ('correo.asunto', 'en', 'Lot lease on Calle Novena'),
  ('correo.asunto_form', 'es', 'Renta de terreno – {nombre}'),
  ('correo.asunto_form', 'en', 'Lot lease – {nombre}'),
  ('aria.whats_flotante', 'es', 'Escribir por WhatsApp'),
  ('aria.whats_flotante', 'en', 'Message us on WhatsApp'),
  ('pie.texto', 'es', 'Terrenos en renta en Calle Novena, Mexicali, B.C.'),
  ('pie.texto', 'en', 'Land for lease on Calle Novena, Mexicali, B.C.')
;
